name = "TransitionPathTheory"
uuid = "8e25bcd3-68d4-49ab-a21a-eececf317700"
authors = ["Gage Bonner <gage.bonner@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
